### PR TITLE
overlay: Update Telecomm service config

### PR DESCRIPTION
**Pull request by andy-de**
Revert audio speedup on mt call patches from qcom

AOSP has their own implementation now in 5.1.1_r37

See: https://review.cyanogenmod.org/#/c/139451

### CODE REVIEW

**Comment by Kra1o5** [comment]
Hi @andy-de ,

What commit want you to merge?

**Comment by andy-de** [comment]
This one: https://github.com/piccolo-dev/android_device_bq_piccolo/pull/82/commits/8e165c7603ca377e1f90f34730b07a1454e696f9

I have no idea, why the commit "Update OTA Url" is in this PR. (It was a commit I made after I had opened the pull request)

**Comment by Kra1o5** [comment]
Hi @andy-de ,
Dont worry, merged here: https://github.com/piccolo-dev/android_device_bq_piccolo/commit/7b9352ce4c1bd6c44b0528358f92cf33fe29e418

Greetings

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#83

**Pull request closed without merging**
