### PR TITLE
sepolicy: Fix sensord permissions

### PR DESCRIPTION
**Pull request by djselbeck**
Change-Id: If8652bee16b156553ff70253a58783b133b9038e

### CODE REVIEW

**Comment by djselbeck** [comment]
Sensord isn't allowed writing in /data/misc/sensor. After that system_server needs to be allowed to rw sensord's fifo_files. This fixes it and all the sensors work again

**Comment by Kra1o5** [comment]
Thanks! @djselbeck .

Merged

**Comment by Kra1o5** [comment]
Yes, atmel_ts service need a domain too.

Is the only bug left to have selinux fully working without denials.

**Comment by stucki** [comment]
This issue was moved to bq-dev/android_device_bq_piccolo#41

**Pull request merged**
